/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app.html",
    "./src/pages/AuditPage.jsx",
    "./src/pages/RankPage.jsx",
    "./src/pages/ImprovePage.jsx",
    "./src/pages/UpgradePage.jsx",
    "./src/pages/UpgradeSuccessPage.jsx",
    "./src/pages/PaymentFailurePage.jsx",
    "./src/pages/PlanChangePage.jsx",
    "./src/pages/PlanChangeSuccessPage.jsx",
    "./src/pages/AccountSettingsPage.jsx",
    "./src/pages/AccountDeletedPage.jsx",
    "./src/pages/EmbedWidgetPage.jsx",
    "./src/pages/EmbedFormPage.jsx",
    "./src/pages/LeadsPage.jsx",
    "./src/pages/LeadDetailPage.jsx",
    "./src/pages/SignInPage.jsx",
    "./src/pages/SignUpPage.jsx",
    "./src/pages/ResetPasswordPage.jsx",
    "./src/pages/VerifyEmailPage.jsx",
    "./src/pages/TeamSettingsPage.jsx",
    "./src/pages/AnalyticsPage.jsx",
    "./src/pages/InviteAcceptPage.jsx",
    "./src/pages/InviteAcceptedPage.jsx",
    "./src/pages/SharedReportPage.jsx",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/layouts/**/*.{js,jsx,ts,tsx}",
    "./src/routes/**/*.{js,jsx,ts,tsx}",
    "./src/index.css",
    "./src/styles/app.css"
  ],
  theme: { extend: {} },
  plugins: [],
};
