import { test, expect } from "@playwright/test";

/**
 * Phase 4 — Distribution & Conversion E2E Tests
 * 
 * Acceptance tests that verify all Phase 4 functionality works together
 * as a real user would experience it.
 * 
 * Test Environment:
 * - Frontend: http://localhost:5173
 * - Backend: http://localhost:3000
 * - No auth required (dev mode)
 */

/**
 * Helper: Wait for audit to complete
 * Polls for audit results by checking for SEO score visibility and result sections
 */
async function waitForAuditComplete(page, timeout = 60000) {
  await expect(page.getByTestId("observed-data")).toBeVisible({ timeout });
  await expect(page.getByTestId("key-issues").first()).toBeVisible({ timeout });
}
test.describe("Phase 4 — Distribution & Conversion", () => {
  test.describe("4.0 Landing Page Instant Audit", () => {
    test("Landing page URL input routes to audit", async ({ page }) => {
      await page.goto("/", { waitUntil: "domcontentloaded" });

      const urlInput = page.getByPlaceholder(/example\.com/i).or(
        page.locator('input[type="text"]')
      ).first();
      await expect(urlInput).toBeVisible({ timeout: 10000 });

      const ctaButton = page.getByRole("button", { name: /Run Free Audit/i });
      await expect(ctaButton).toBeDisabled();

      await urlInput.fill("https://example.com");
      await expect(ctaButton).toBeEnabled({ timeout: 2000 });
      await ctaButton.click();

      await expect(page).toHaveURL(/\/audit/, { timeout: 10000 });
      const url = page.url();
      expect(url).toContain("url=");
      expect(url).toContain("example.com");
    });
  });

  test.describe("4.1 Shared Report Acquisition", () => {
    test("Shared report loads and converts", async ({ page }) => {
      // Navigate to known valid shared report URL
      const reportId = "b2c7fcc7fef8844821e0b335b94a516a";
      await page.goto(`/r/${reportId}`, { waitUntil: "domcontentloaded" });

      // Assert: Page loads
      await expect(page).toHaveURL(new RegExp(`/r/${reportId}`), { timeout: 10000 });

      // Assert: Text exists - "Generated by RankyPulse"
      const attributionLink = page
        .getByRole("link", { name: /Generated by RankyPulse/i })
        .first();
      await expect(attributionLink).toBeVisible({ timeout: 10000 });

      // Assert: "Run Free Audit" button exists
      const runFreeAuditButton = page.getByRole("button", { name: /Run Free Audit/i });
      await expect(runFreeAuditButton.first()).toBeVisible({ timeout: 10000 });

      // Assert: Report score is visible
      await expect(page.getByText('SEO Score', { exact: true })).toBeVisible({ timeout: 10000 });
      
      // The score section should be visible (score value may be a number or "—")
      const scoreSection = page.getByText('SEO Score', { exact: true });
      await expect(scoreSection).toBeVisible({ timeout: 5000 });

      // Click "Run Free Audit"
      await runFreeAuditButton.first().click();

      // Assert: Browser navigates to /audit
      await expect(page).toHaveURL(/\/audit/, { timeout: 10000 });

      // Assert: URL contains no auth requirements (no /admin, no auth tokens)
      const url = page.url();
      expect(url).not.toContain("/admin");
      expect(url).not.toMatch(/auth|token|login/i);
    });
  });

  test.describe("4.2 Start Page Conversion", () => {
    test("Start page accepts URL and routes to audit", async ({ page }) => {
      // Navigate to /start
      await page.goto("/start", { waitUntil: "domcontentloaded" });

      // Assert: Headline exists
      await expect(page.getByText(/Run a free SEO audit/i)).toBeVisible({ timeout: 10000 });

      // Assert: URL input exists
      const urlInput = page.getByPlaceholder(/example\.com/i).or(
        page.locator('input[type="text"]')
      ).first();
      await expect(urlInput).toBeVisible({ timeout: 10000 });

      // Assert: CTA disabled when input empty
      const ctaButton = page.getByRole("button", { name: /Run Free Audit/i });
      await expect(ctaButton).toBeDisabled();

      // Fill input with https://example.com
      await urlInput.fill("https://example.com");

      // Assert: CTA is now enabled (wait a bit for state update)
      await expect(ctaButton).toBeEnabled({ timeout: 2000 });

      // Click "Run Free Audit"
      await ctaButton.click();

      // Assert: Navigates to /audit
      await expect(page).toHaveURL(/\/audit/, { timeout: 10000 });

      // Assert: URL query includes url=
      const url = page.url();
      expect(url).toContain("url=");
      expect(url).toContain("example.com");
    });
  });

  test.describe("4.3 Post-Audit Conversion Panel", () => {
    test("Conversion panel appears once after audit", async ({ page }) => {
      // Clear session storage to ensure fresh state
      await page.context().clearCookies();

      // Go directly to /audit?url=https://example.com
      await page.goto("/audit?url=https://example.com", { waitUntil: "domcontentloaded" });

      await page.evaluate(() => {
        sessionStorage.clear();
        localStorage.clear();
      });

      // Wait for audit results to appear
      await waitForAuditComplete(page);

      // Assert: SEO score visible
      await expect(page.getByText('SEO Score', { exact: true })).toBeVisible({ timeout: 10000 });

      // Assert: Issues or quick wins rendered      // Assert: audit results sections exist (stable anchors)
      await expect(page.getByTestId("observed-data")).toBeVisible({ timeout: 60000 });
      const hasQuickWins = await page.getByText("Quick Wins", { exact: true }).isVisible().catch(() => false);
      const hasIssuesPanel = await page.getByTestId("key-issues").first().isVisible().catch(() => false);
      expect(hasQuickWins || hasIssuesPanel).toBe(true);
// Assert: Conversion panel exists
      await expect(page.getByText(/Save your audit & track improvements/i)).toBeVisible({ timeout: 10000 });

      // Assert: Email input visible
      const emailInput = page.getByPlaceholder(/Email address/i).or(
        page.locator('input[type="email"]')
      ).first();
      await expect(emailInput).toBeVisible({ timeout: 5000 });

      // Assert: "Email me updates" CTA exists
      await expect(page.getByRole("button", { name: /Email me updates/i })).toBeVisible({ timeout: 5000 });

      // Assert: "Not now" secondary button exists
      const notNowButton = page.getByRole("button", { name: /Not now/i });
      await expect(notNowButton).toBeVisible({ timeout: 5000 });

      // Click "Not now"
      await notNowButton.click();

      // Assert: Panel disappears
      await expect(page.getByText(/Save your audit & track improvements/i)).not.toBeVisible({ timeout: 5000 });

      // Reload page
      await page.reload({ waitUntil: "domcontentloaded" });

      // Wait for audit to complete again (it should auto-run)
      await waitForAuditComplete(page);

      // Assert: Panel does NOT reappear on page reload
      await expect(page.getByText(/Save your audit & track improvements/i)).not.toBeVisible({ timeout: 3000 });
    });
  });

  test.describe("Phase 4 End-to-End Flow", () => {
    test("Cold visitor → value → conversion", async ({ page }) => {
      // Clear all storage for fresh start
      await page.context().clearCookies();

      // Visit homepage /
      await page.goto("/", { waitUntil: "domcontentloaded" });

      await page.evaluate(() => {
        sessionStorage.clear();
        localStorage.clear();
      });

      // Click primary CTA
      const primaryCTA = page.getByRole("link", { name: /Run an Audit/i }).or(
        page.getByRole("button", { name: /Run an Audit/i })
      ).first();
      await expect(primaryCTA).toBeVisible({ timeout: 10000 });
      await primaryCTA.click();

      // Assert: Navigates to /start
      await expect(page).toHaveURL(/\/start/, { timeout: 10000 });

      // Enter URL → run audit
      const startForm = page.locator("form").first();
      const inputSelector = 'input[placeholder="https://example.com"]';
      await page.waitForSelector(inputSelector, { state: "visible", timeout: 10000 });
      await page.fill(inputSelector, "https://example.com");
      await page.waitForFunction((sel) => {
        const el = document.querySelector(sel);
        return el && el.value && el.value.includes("example.com");
      }, inputSelector, { timeout: 10000 });

      const runButton = startForm.getByRole("button", { name: /Run Free Audit/i });
      await expect(runButton).toBeEnabled({ timeout: 10000 });
      await runButton.click();

      // Wait for audit results
      await waitForAuditComplete(page);

      // Assert: Conversion panel shown
      await expect(page.getByText(/Save your audit & track improvements/i)).toBeVisible({ timeout: 10000 });

      // Dismiss panel
      const notNowButton = page.getByRole("button", { name: /Not now/i });
      await notNowButton.click();
      await expect(page.getByText(/Save your audit & track improvements/i)).not.toBeVisible({ timeout: 5000 });

      // Navigate back to homepage
      await page.goto("/", { waitUntil: "domcontentloaded" });

      // Re-open shared report
      const reportId = "b2c7fcc7fef8844821e0b335b94a516a";
      await page.goto(`/r/${reportId}`, { waitUntil: "domcontentloaded" });

      // Assert: Shared report still works
      const attributionLink = page
        .getByRole("link", { name: /Generated by RankyPulse/i })
        .first();
      await expect(attributionLink).toBeVisible({ timeout: 10000 });
      await expect(page.getByText('SEO Score', { exact: true })).toBeVisible({ timeout: 10000 });

      // Assert: Attribution links to /start
      const footerAttributionLink = page.getByRole("link", { name: /Generated by RankyPulse/i }).first();
      await expect(footerAttributionLink).toBeVisible({ timeout: 5000 });
      
      const href = await footerAttributionLink.getAttribute("href");
      expect(href).toBe("/start");
    });
  });

  test.describe("4.4 Content Marketing Use Cases", () => {
    const pages = [
      "/use-cases/saas-landing-audit",
      "/use-cases/blog-audit-checklist",
      "/use-cases/agency-audit-workflow",
    ];

    for (const path of pages) {
      test(`Use-case page has audit CTA: ${path}`, async ({ page }) => {
        await page.goto(path, { waitUntil: "domcontentloaded" });
        const cta = page.getByRole("link", { name: /Run Free Audit/i }).or(
          page.getByRole("button", { name: /Run Free Audit/i })
        ).first();
        await expect(cta).toBeVisible({ timeout: 10000 });
      });
    }
  });
});
