import { lazy, Suspense, useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { track } from "../lib/eventsClient.js";
import AppShell from "../components/AppShell.jsx";
import { IconPlay, IconArrowRight } from "../components/Icons.jsx";
import { safeJson } from "../lib/safeJson.js";

const IssuesPanel = lazy(() => import("../components/IssuesPanel.jsx"));

export default function SharedReportPage() {
  const { reportId } = useParams();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (reportId) {
      track("share_report_viewed", {
        scope: "",
        meta: { reportId }
      });
    }
  }, [reportId]);

  useEffect(() => {
    async function loadReport() {
      if (!reportId) {
        setError("Invalid report ID");
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        const res = await fetch(apiUrl(`/api/shared-reports/${reportId}`));
        
        if (!res.ok) {
          if (res.status === 404) {
            setError("Report not found. It may have expired or been deleted.");
          } else {
            setError("Failed to load report.");
          }
          setLoading(false);
          return;
        }

        const data = await safeJson(res);
        if (data.ok && data.report) {
          setReport(data.report);
        } else {
          setError("Invalid report data.");
        }
      } catch (err) {
        setError("Failed to load report.");
        if (process.env.NODE_ENV !== "production") {
          console.error("Failed to load shared report:", err);
        }
      } finally {
        setLoading(false);
      }
    }

    loadReport();
  }, [reportId]);

  const issues = Array.isArray(report?.issues) ? report.issues : [];
  const quickWins = Array.isArray(report?.quick_wins) ? report.quick_wins : [];
  const brief = typeof report?.content_brief === "string" ? report.content_brief : null;
  const isReady = !loading && report && !error;
  const hasError = !loading && (error || !report);

  const handleRunAuditClick = () => {
    track("shared_report_cta_clicked", {
      scope: "",
      meta: { reportId, cta: "run_audit" }
    });
    window.location.href = "/audit";
  };

  const handleUpgradeClick = () => {
    track("shared_report_cta_clicked", {
      scope: "",
      meta: { reportId, cta: "upgrade" }
    });
    navigate("/upgrade");
  };

  return (
    <>
      <div data-testid="shared-cta-strip" className="mb-4 flex items-center justify-between gap-3">
        <a href="/start" className="text-xs text-[var(--rp-text-500)] hover:text-[var(--rp-text-900)] hover:underline">Generated by RankyPulse</a>
        <div className="flex items-center gap-3">
          <div className="text-sm font-semibold text-[var(--rp-text-700)]">Score preview</div>
          <button
            type="button"
            onClick={handleRunAuditClick}
            className="rp-btn-primary text-sm"
          >
            Run Free Audit
          </button>
        </div>
      </div>
      <AppShell title="Shared SEO Audit Report" subtitle={isReady ? `Report for ${report.url || "unknown URL"}` : "Shared report"}>
        <div className="flex flex-col gap-4">
          {loading && (
            <div className="rp-card p-5 text-[var(--rp-text-600)]">
              Loading report...
            </div>
          )}
          {hasError && (
            <div className="rounded-2xl border border-rose-300/60 bg-rose-100/70 p-5 text-rose-700">
              {error || "Report not found"}
            </div>
          )}
          {isReady && (
            <>
              <div className="grid gap-4 md:grid-cols-4">
                {[
                  { label: "SEO health", value: report.score ?? "—", tone: "text-emerald-600" },
                  { label: "Issues found", value: issues.length, tone: "text-rose-600" },
                  { label: "Quick wins", value: quickWins.length, tone: "text-amber-600" },
                  { label: "Impact forecast", value: "+24%", tone: "text-[var(--rp-indigo-700)]" }
                ].map((item) => (
                  <div key={item.label} className="rp-kpi-card rounded-2xl border border-[var(--rp-border)] bg-white p-4 shadow-sm">
                    <div className="text-xs text-[var(--rp-text-500)]">{item.label}</div>
                    <div className={`mt-2 text-2xl font-semibold ${item.tone}`}>{item.value}</div>
                  </div>
                ))}
              </div>
              {/* Branding + CTA Banner */}
              <div className="rp-card rp-kpi-card p-4">
                <div className="mb-3 text-xs text-[var(--rp-text-500)]">
                  <Link to="/start" className="hover:underline text-[var(--rp-text-700)]">Generated by RankyPulse</Link> - see how this report was created by running your own audit in under 30 seconds.
                </div>
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                  <div>
                    <div className="text-sm font-semibold text-[var(--rp-text-700)]">Run your own audit</div>
                    <div className="text-xs text-[var(--rp-text-500)]">Get unlimited audits and fix actions with Pro</div>
                  </div>
                    <div className="flex flex-col sm:flex-row gap-2">
                      <div className="flex flex-col">
                        <button
                          onClick={handleRunAuditClick}
                          className="rp-btn-primary text-sm"
                        >
                          <IconPlay size={14} />
                          Run Free Audit
                        </button>
                        <div className="mt-1 rp-body-xsmall text-center">You'll see your SEO score, key issues, and quick wins instantly.</div>
                      </div>
                      <button
                        onClick={async () => {
                          const mod = await import("../utils/exportAuditPdf.js");
                          mod.exportAuditPdf(report);
                        }}
                        className="rp-btn-secondary text-sm"
                      >
                        Export PDF
                      </button>
                      <div className="flex flex-col">
                        <button
                          onClick={handleUpgradeClick}
                          className="rp-btn-secondary text-sm"
                        >
                          <IconArrowRight size={14} />
                          Upgrade to Pro
                        </button>
                        <div className="mt-1 rp-body-xsmall text-center">
                          Unlock fix plans, exports, and tracking immediately after checkout.
                        </div>
                      </div>
                  </div>
                </div>
              </div>

              {/* Score and Quick Wins */}
              <div className="grid gap-4 md:grid-cols-3">
                <div className="rp-card p-5">
                  <div className="rp-section-title">SEO Score</div>
                  <div className="mt-2 text-4xl font-semibold text-[var(--rp-text-900)]">
                    {typeof report.score === "number" ? report.score : "-"}
                  </div>
                </div>

                <div className="md:col-span-2 rp-card p-5">
                  <div className="rp-section-title">Quick Wins</div>
                  <div className="mt-3">
                    {quickWins.length > 0 ? (
                      <ul className="list-disc space-y-2 pl-5 text-[var(--rp-text-600)]">
                        {quickWins.slice(0, 10).map((x, i) => (
                          <li key={i}>{x}</li>
                        ))}
                      </ul>
                    ) : (
                      <div className="text-[var(--rp-text-500)]">No quick wins available.</div>
                    )}
                  </div>
                </div>
              </div>

              {/* Issues Panel */}
              {issues.length > 0 && (
                <Suspense fallback={null}>
                  <IssuesPanel issues={issues} />
                </Suspense>
              )}

              {/* Content Brief */}
              {brief && (
                <div className="rp-card p-5">
                  <div className="rp-section-title mb-3">Content Brief</div>
                  <div className="whitespace-pre-wrap text-[var(--rp-text-700)]">{brief}</div>
                </div>
              )}

              {/* Footer CTA */}
              <div className="rp-card p-5 text-center">
                <div className="text-xs text-[var(--rp-text-500)] mb-2">
                  <Link to="/start" className="hover:underline text-[var(--rp-text-700)]">Generated by RankyPulse</Link> - see how this report was created by running your own audit in under 30 seconds.
                </div>
                <div className="text-sm text-[var(--rp-text-600)] mb-3">
                  Want to run your own audits and fix issues?
                </div>
                <div className="flex flex-col sm:flex-row gap-3 justify-center items-center">
                  <div className="flex flex-col">
                    <button
                      onClick={handleRunAuditClick}
                      className="rp-btn-primary text-sm"
                    >
                      Run Free Audit
                    </button>
                    <div className="mt-1 rp-body-xsmall text-center">You'll see your SEO score, key issues, and quick wins instantly.</div>
                  </div>
                  <button
                    onClick={async () => {
                      const mod = await import("../utils/exportAuditPdf.js");
                      mod.exportAuditPdf(report);
                    }}
                    className="rp-btn-secondary text-sm"
                  >
                    Export PDF
                  </button>
                  <div className="flex flex-col">
                    <button
                      onClick={handleUpgradeClick}
                      className="rp-btn-secondary text-sm"
                    >
                      Upgrade to Pro
                    </button>
                    <div className="mt-1 rp-body-xsmall text-center text-[var(--rp-text-500)]">
                      Unlock fix plans, exports, and tracking immediately after checkout.
                    </div>
                  </div>
                </div>
              </div>
            </>
          )}
        </div>
      </AppShell>
    </>
  );
}
