import { useEffect, useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { track } from "../lib/eventsClient.js";
import AppShell from "../components/AppShell.jsx";
import IssuesPanel from "../components/IssuesPanel.jsx";

export default function SharedReportPage() {
  const { reportId } = useParams();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (reportId) {
      track("share_report_viewed", {
        scope: "",
        meta: { reportId }
      });
    }
  }, [reportId]);

  useEffect(() => {
    async function loadReport() {
      if (!reportId) {
        setError("Invalid report ID");
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        const res = await fetch(`/api/shared-reports/${reportId}`);
        
        if (!res.ok) {
          if (res.status === 404) {
            setError("Report not found. It may have expired or been deleted.");
          } else {
            setError("Failed to load report.");
          }
          setLoading(false);
          return;
        }

        const data = await res.json();
        if (data.ok && data.report) {
          setReport(data.report);
        } else {
          setError("Invalid report data.");
        }
      } catch (err) {
        setError("Failed to load report.");
        if (process.env.NODE_ENV !== "production") {
          console.error("Failed to load shared report:", err);
        }
      } finally {
        setLoading(false);
      }
    }

    loadReport();
  }, [reportId]);

  const issues = Array.isArray(report?.issues) ? report.issues : [];
  const quickWins = Array.isArray(report?.quick_wins) ? report.quick_wins : [];
  const brief = typeof report?.content_brief === "string" ? report.content_brief : null;

  if (loading) {
    return (
      <>
        <div data-testid="shared-cta-strip" className="mb-4 flex items-center justify-between gap-3">
          <a href="/start" className="text-xs text-white/60 hover:text-white hover:underline">Generated by RankyPulse</a>
          <div className="flex items-center gap-3">
            <div className="text-sm font-semibold text-white/80">SEO Score</div>
            <button
              type="button"
              onClick={() => (window.location.href = "/start")}
              className="rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90"
            >
              Run Free Audit
            </button>
          </div>
        </div>

        <AppShell title="Shared Report" subtitle="Loading report...">
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-white/70">
            Loading report...
          </div>
        </AppShell>
      </>
    );
  }
  if (error || !report) {
    return (
      <AppShell title="Shared Report" subtitle="Report not found">
        <div className="rounded-2xl border border-rose-400/30 bg-rose-500/10 p-5 text-rose-100">
          {error || "Report not found"}
        </div>
        <div className="mt-4">
          <button
            type="button"
            onClick={() => (window.location.href = "/start")}
            className="rounded-2xl bg-white px-4 py-2 text-sm font-semibold text-black hover:bg-white/90"
          >
            Run Free Audit
          </button>
        </div>
      </AppShell>
    );
  }

  const handleRunAuditClick = () => {
    track("shared_report_cta_clicked", {
      scope: "",
      meta: { reportId, cta: "run_audit" }
    });
    navigate("/audit");
  };

  const handleUpgradeClick = () => {
    track("shared_report_cta_clicked", {
      scope: "",
      meta: { reportId, cta: "upgrade" }
    });
    navigate("/upgrade");
  };

  return (
    <AppShell title="Shared SEO Audit Report" subtitle={`Report for ${report.url || "unknown URL"}`}>
      <div className="flex flex-col gap-4">
        {/* Branding + CTA Banner */}
        <div className="rounded-2xl border border-indigo-400/30 bg-indigo-500/10 p-4">
          <div className="mb-3 text-xs text-indigo-200/90">
            <Link to="/start" className="hover:underline">Generated by RankyPulse</Link> — see how this report was created by running your own audit in under 30 seconds.
          </div>
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <div className="text-sm font-semibold text-indigo-200">Run your own audit</div>
              <div className="text-xs text-indigo-300/80">Get unlimited audits and fix actions with Pro</div>
            </div>
            <div className="flex flex-col sm:flex-row gap-2">
              <div className="flex flex-col">
                <button
                  onClick={handleRunAuditClick}
                  className="rounded-xl bg-gradient-to-r from-indigo-500 to-fuchsia-500 px-4 py-2 text-sm font-semibold text-white transition hover:opacity-95"
                >
                  Run Free Audit
                </button>
                <div className="mt-1 text-xs text-indigo-300/60 text-center">You'll see your SEO score, key issues, and quick wins instantly.</div>
              </div>
              <button
                onClick={handleUpgradeClick}
                className="rounded-xl border border-white/20 bg-white/5 px-4 py-2 text-sm font-semibold text-white/70 transition hover:bg-white/10 hover:text-white/90"
              >
                Upgrade to Pro
              </button>
            </div>
          </div>
        </div>

        {/* Score and Quick Wins */}
        <div className="grid gap-4 md:grid-cols-3">
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <div className="text-sm font-semibold text-white/80">SEO Score</div>
            <div className="mt-2 text-4xl font-semibold">
              {typeof report.score === "number" ? report.score : "—"}
            </div>
          </div>

          <div className="md:col-span-2 rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <div className="text-sm font-semibold text-white/80">Quick Wins</div>
            <div className="mt-3">
              {quickWins.length > 0 ? (
                <ul className="list-disc space-y-2 pl-5 text-white/85">
                  {quickWins.slice(0, 10).map((x, i) => (
                    <li key={i}>{x}</li>
                  ))}
                </ul>
              ) : (
                <div className="text-white/60">No quick wins available.</div>
              )}
            </div>
          </div>
        </div>

        {/* Issues Panel */}
        {issues.length > 0 && (
          <IssuesPanel issues={issues} />
        )}

        {/* Content Brief */}
        {brief && (
          <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <div className="text-sm font-semibold text-white/80 mb-3">Content Brief</div>
            <div className="whitespace-pre-wrap text-white/85">{brief}</div>
          </div>
        )}

        {/* Footer CTA */}
        <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-center">
          <div className="text-xs text-white/60 mb-2">
            <Link to="/start" className="hover:underline">Generated by RankyPulse</Link> — see how this report was created by running your own audit in under 30 seconds.
          </div>
          <div className="text-sm text-white/70 mb-3">
            Want to run your own audits and fix issues?
          </div>
          <div className="flex flex-col sm:flex-row gap-3 justify-center items-center">
            <div className="flex flex-col">
              <button
                onClick={handleRunAuditClick}
                className="rounded-xl bg-gradient-to-r from-indigo-500 to-fuchsia-500 px-6 py-3 text-sm font-semibold text-white transition hover:opacity-95"
              >
                Run Free Audit
              </button>
              <div className="mt-1 text-xs text-white/50 text-center">You'll see your SEO score, key issues, and quick wins instantly.</div>
            </div>
            <button
              onClick={handleUpgradeClick}
              className="rounded-xl border border-white/20 bg-white/5 px-6 py-3 text-sm font-semibold text-white/70 transition hover:bg-white/10 hover:text-white/90"
            >
              Upgrade to Pro
            </button>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
